maximevaillancourt/digital-garden-jekyll-template

_notes/your-first-note.md, _plugins/bidirectional_links_generator.rb
Relates to https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/31
This pull request adds support for optional labels in double-bracket links.
=> Add support for optional label in double-bracket links

_plugins/empty_front_matter_note_injector.rb
Hi Maxime,
enjoy your template; thanks for sharing it!
I noticed that the plugin that inserts front matter to notes that don't have it, writes all notes to disk anyway, whether they already have it or not. That changes the modified time for the original Markdown note files in the _notes/ folder. At least for my workflow that meant that my editor could no longer meaningfully sort all notes by last modified date, because they all had the same time and date — that of the last time I generated the site with Jekyll.
Not sure if you accept pull requests, but if you do, here's a fix for that. Straightforward, just skipping the write step if the note already has front matter. I guess that also makes it run faster, but you'd have to have lots of notes for that to matter…
Have a great day,
Stefan
=> Skip unnecessary rewrites of notes in `empty_front_matter_note_injector.rb`

_config.yml, _includes/head.html, _includes/nav.html, _layouts/note.html, _plugins/bidirectional_links_generator.rb
One of the breaking errors that I fixed in my install of this great repo was that all links generated by the ruby script didn't take into account the baseurl specified in the config file.
This ruby file corrects the error, although in the paths it might add one '/' too many. This hasn't caused me any issues, but should be considered.
=> Update generator to include baseurl.

Gemfile, Gemfile.lock, _config.yml, _notes/your-first-note.md, _plugins/open_external_links_in_new_tab.rb
This pull request adds a `open_external_links_in_new_tab` option, which automatically adds a `target="blank"` attribute to external links so that browsers open them in new tabs.
=> Add option to open external links in new tab

_notes/your-first-note.md, _plugins/open_external_links_in_new_tab.rb, _sass/_style.scss
Update to treat the classes .footnote and .reversefootnote the same as the internal-link class. With the current default settings, the classes are treated as external links and then a new page is opened when the footnote or reverse footnote link are clicked.
To test, add a footnote on a markdown page.[^1]
[^1]: this is a footnote
=> Treat footnotes as internal links

_sass/_code.scss
This allows divs containing preformatted codeblocks to scroll horizontally. For an example of the non-scrolling current behavior, look at the shell script on [this note page](https://digital-garden-jekyll-template.netlify.app/your-first-note) with browser <1100px. The div containing a preformatted block is not resizing with the grid, which is preventing the backlinks box from being visible. This is also a problem on mobile devices, since horizontal scrolling of the body is not allowed.
This fix, `display: grid`, allows the div.highlight element to resize along with the grid container, fixing both the responsive backlink box issue and horizontal scrolling of the codeblock for browser widths <600px.
For a working demo, scroll down on [my garden …
=> pre codeblock horizontal scroll

_plugins/bidirectional_links_generator.rb
Feel free to ignore this pull request in case you were already aware of `!` and exerting a coding style opinion.
The following are equivalent, as far as I understand, so some chars can be deleted 🙂:
`current_note.content = current_note.content.gsub()` == `current_note.content.gsub!()`
=> gsub -> gsub!

_config.yml, _notes/your-first-note.md, _plugins/embed_tweets.rb
This pull request adds a new site configuration flag to allow replacing tweet URLs on their own lines with official Twitter embeds. This behavior is however disabled by default for privacy reasons.
Here's how it looks like when enabled and the browser is configured to allow external content:
Here's how it looks like when enabled but the browser blocks external content:
Here's how it looks like when disabled altogether (`embed_tweets: false` in `_config.yml`):
cc @kolanuts
=> Allow embedding tweets

_notes/your-first-note.md, _plugins/markdown-highlighter.rb
Fixes https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/73
This pull request adds highlighting for content wrapped with `==`.
Input:
```
You can also ==highlight some content== by wrapping it with `==`.
```
Output:
=> Highlight content wrapped with ==

_notes/your-first-note.md, _plugins/bidirectional_links_generator.rb
This fixes https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/83.
The newlines in the inserted string would break Jekyll's way of generating footnotes with wikilinks in them.
The fix is to remove these newlines to ensure Jekyll doesn't mess with the inserted HTML.
=> Fix links to notes in footnotes

_plugins/bidirectional_links_generator.rb
The titles of notes can contain characters that have a special meaning
in regular expressions. Therefore those characters have to be escaped
before the title is used in a regular expression. Failure to do so in
the code that replaces wikilinks in notes can otherwise result in
broken links.
=> Fix certain wikilinks

_includes/notes_graph.html
We should compare the `id` attribute instead of the node object. 
These bugs casues:
1. all nodes to have the same weights.
2. edges to be duplicated? (i haven't spent time trying to see the effect of this)
=> fix: missing .id from nodes

_notes/your-first-note.md, _notes/안녕하세요.md, _plugins/bidirectional_links_generator.rb
This pull request fixes https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/100 by adding support for non-latin note titles.
=> Add support for non-latin note titles

_notes/your-first-note.md, _plugins/bidirectional_links_generator.rb
Supersedes https://github.com/maximevaillancourt/digital-garden-jekyll-template/pull/95.
Allows links to include underscores and hyphens.
=> Allow using `-` and `_` in links

_plugins/open_external_links_in_new_tab.rb
Some browsers might interpret "blank" as a named frame. You might want to consider using the browser standard _blank
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target
=> Use _blank for the target

_sass/_code.scss
before:
after:
now `code` tag is padded, so the `code` of `highlight` has no left alignment, I think it would be better to be consistent.
=> code block left alignment

_plugins/open_external_links_in_new_tab.rb
Closes issue #116
Use `inner_html` instead of `to_html` to prevent Nokogiri from wrapping the content in HTML DOCTYPE
=> Fix issue with full HTML + DOCTYPE being inserted

Gemfile.lock
Liquid 4.0.3 does not fully support Ruby 3.2. See: https://github.com/jekyll/jekyll/issues/9233
This PR upgrades Liquid to 4.0.4, fixing this issue while still maintaining complete backwards compatibility.
=> Fix Exception when running Ruby 3.2

_pages/index.md
When generating using this template, the following warning appears:
`Liquid Warning: Liquid syntax error (line 15): Expected end_of_string but found pipe in "note in recent_notes | limit: 5" in _pages/index.md`
This happens regardless of the amount of notes that exist.
This PR fixes this warning, while not affecting the functionality.
--
Thank you for this template, it is very well thought out. :heart:
=> Fix Liquid syntax error

_includes/notes_graph.html
- Its "hitbox" actually extends to the right of the page, meaning that scrolling on the right edge of the page would override the page scroll and instead zoom the graph
- An annoying small bottom margin is present, adding `display: block;` fixes it.  
*(It might be due to some obscure `vertical-align` or `line-height`, but setting its display to block does not harm whatsoever and fixes the issue)*
=> Fix the note graph's layout

_includes/notes_graph.html
Fix https://github.com/maximevaillancourt/digital-garden-jekyll-template/issues/148
Ultimately prevents `Uncaught SyntaxError: unterminated regular expression literal`.
=> Prevent conflict between markdown highlight plugin and notes_graph JavaScript

_includes/notes_graph.html, _notes/your-first-note.md, _plugins/markdown-highlighter.rb
Fix #148 (for real)
- JavaScript code snippet renders as expected
- Markdown highlights render as expected
- No error in the console
=> Actually prevent Markdown highlight conflict

_sass/_code.scss
For some reason, single quotation marks are marked as `.dl` and separate from the actual string (here, `.s1`); but double quotation marks are part of the same element as the string itself (`.s2`)
This PR fixes this absolutely minor detail that probably nobody ever noticed :joy:
Fixed:
=> Fix string delimiters being unstyled in code blocks

.github/workflows/jekyll.yml, 404.html, README.md, _config.yml, _includes/footer.html, _notes/your-first-note.md, _pages/index.md
- fix recent notes url
- allow digital garden to be deployed and hosted on github pages!
- fix url for assets
- remove misleading instructions
- clarify the new from the old text on the README using the new NOTE highlight box
- fix footer link as well
- fix 404 as well
- this fixes #176 
- this fixes #58
=> Easy Github Pages

_plugins/open_external_links_in_new_tab.rb
Prevents the creation of unnecessary `<html>` and `<body>` tags when `open_external_links_in_new_tab` config option is set to `true`.
May fix #196.
=> Parse document as fragment

_plugins/bidirectional_links_generator.rb
If the current note has a link to an image, a bad backlink will be generated from the given note to itself. This change prevents the current note from creating a backlink to itself for any reason.
This can be seen in the netlify sample site: https://digital-garden-jekyll-template.netlify.app/your-first-note
=> Ignore current note when generating backlinks
